server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  # ? ??? default? true -> ?? ??? ?????? ???? ?? ?? ?? ??
  client:
    register-with-eureka: false
    fetch-registry: false